### ISSUE TITLE
A version system

### ISSUE THREAD

**Issue by sigv** [totallymike/ircnode#18]
There should exist a version system which would possibly use commits as versions. The `!version` or `!info` command would be integrated into the core and would return small information about the bot and the current version it is running on.

**Comment by totallymike** [comment]
This can be tied easily into package.json.

**Comment by sigv** [comment]
I want it to also use the commit number. The format could be `#.#.# (commit)`. What do you think?

**Comment by sigv** [comment]
Current implementation is in `version_cmd` branch. When the user enters `!version`, `IRC Node #.#.#` is output. If for any reason the version couldn't be determined (most likely because the npm `package.json` file could not be found), the message output is `IRC Node (unknown version)`.

**Comment by sigv** [comment]
Closing as merged into `master`. This is included in the core and prefers to respond using the commit number, if it looks like a git repo.
