### ISSUE TITLE
Needs documentation.

### ISSUE THREAD

**Issue by totallymike** [totallymike/ircnode#2]
'nuff said.

**Comment by sigv** [comment]
The documentation about the current configuration setup and installation steps has been added to the wiki. The developers' documentation and information is coming soon.

**Comment by sigv** [comment]
Basic plugin API documentation is available [here](https://github.com/totallymike/ircnode/wiki/PluginAPI). Any changes or suggestions?
More developer information is on the way.

**Comment by sigv** [comment]
Closing issue as [plugin development](https://github.com/totallymike/ircnode/wiki/PluginDevelopment) page has been created covering basic information such as the plugin skeleton, the action parameter given to the handler function and API usage.
All new suggestions/changes go to master right away, go to a new issue or to a fork (+pull request).
