### ISSUE TITLE
A npm package

### ISSUE THREAD

**Issue by sigv** [totallymike/ircnode#21]
Currently the user must download the source. It works fine, but having it available from [npm](http://npmjs.org/) would be much better. It is not a small task, but would make installation more seamless and I believe it would attract many other users.

**Comment by totallymike** [comment]
I'm actually working on packaging it right now.

**Comment by sigv** [comment]
Oh. You are always one step ahead.

**Comment by totallymike** [comment]
Packaged up for publication.  Will not actually publish until milestone dependencies are met, but this issue can now be closed.
