### ISSUE TITLE
Multiple commands from one plugin

### ISSUE THREAD

**Issue by sigv** [totallymike/ircnode#24]
Currently each plugin can only implement one command and as many parameters as the developer wants. This is fine for most situations but large plugins may require multiple commands.

**Comment by theVDude** [comment]
I've just got this working. Cleaning up a bit and making an example plugin for it. The exports on each plugin needs changed a little bit for it to work, but it's early enough on to do that. I'll have a commit up later.

**Comment by sigv** [comment]
Closing as this was merged into master.
