### ISSUE TITLE
PID file location choice/change

### ISSUE THREAD

**Issue by sigv** [totallymike/ircnode#39]
Currently IRC Node always stores it's PID for daemon in the /tmp/ircnode.pid file. This is usually fine, but if the user wants to start multiple daemons on the same computer for any reason (such as for a different irc server or on a shared system, for example, shell account) there will be problems.

I think the PID file should be stored (by default) in `config_path`/daemon.pid, but the `IRC_NODE_PID_FILE` env var should be prefered.

**Comment by totallymike** [comment]
This is good.  The environment variable makes it a little easier to support an lsb-style init script.

**Comment by sigv** [comment]
Got this implemented on the `pid_file_choose` branch.

**Comment by sigv** [comment]
Pull request merged.
