### ISSUE TITLE
Automatically create required files

### ISSUE THREAD

**Issue by sigv** [totallymike/ircnode#4]
The configuration files and folders the bot requires should be automatically created if they do not exist instead of just failing.

**Comment by sigv** [comment]
The changes have been added to a pull request (#8) and are awaiting confirmation.

**Comment by totallymike** [comment]
Having doubts about this one.  A default configuration could quietly lead the bot to a dangerous state.  We'll have to come up with some pretty solid warnings or walk the user through initializing the config/users file.

**Comment by sigv** [comment]
I believe the configuration files could be set to default to freenode #bots room. After creating the configuration files the bot should stop and output information or a link to the documentation of the configuration file setup. Do you agree?

**Comment by totallymike** [comment]
I like that solution.

**Comment by sigv** [comment]
Do you believe that I can merge this into `master` or do you believe more changes are necessary?

**Comment by sigv** [comment]
Closing issue as pull request #11 has done this.
