### ISSUE TITLE
!learn commands

### ISSUE THREAD

**Issue by totallymike** [totallymike/ircnode#7]
I'd like to have a !learn command.  You type !learn or something and pass it some parameters and it remembers the command.

**Comment by sigv** [comment]
I believe the syntax should be `!learn "INPUT" "RESPONSE"`. Quotation marks would be required to put multiple words in a phrase.

**Comment by sigv** [comment]
This implementation has been pushed to the `learn_command` branch.

**Comment by sigv** [comment]
As suggested by the project leader (totallymike), this is being moved down to plugin level. A pull request for this has been opened in the plugins repository ([#4](https://github.com/totallymike/ircnode_plugins/pull/4)).

I'm leaving this issue open until the pull request gets merged into master on the plugins repository.

**Comment by sigv** [comment]
Closing this issue as the plugin was already merged into master.
